language: objective-c
osx_image: xcode9.1
rvm:
  - 2.6
  - ruby-head
before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh